import type { Fund } from './components';

export const mockFunds: Fund[] = [
  {
    id: '1',
    name: 'AMERICAN AMCAPF3: FMACX',
    category: 'Large Cap',
    tier: 1,
    assetClass: 'US Large Cap',
    equitySector: 'Financial',
    asset: 'Growth',
    selected: true,
  },
  {
    id: '2',
    name: 'AMERICAN BALANCED F3 #: AFMBX',
    category: 'Large Cap - View',
    tier: 1,
    assetClass: 'Multiple',
    equitySector: 'Financial',
    asset: 'Blend',
    selected: true,
  },
  {
    id: '3',
    name: 'AMERICAN BOND FUND OF AMER F3: BFFAX',
    category: 'Income',
    tier: 1,
    assetClass: 'Investment Grade Bond',
    equitySector: 'Technology',
    asset: 'Taxable',
    selected: false,
  },
  {
    id: '4',
    name: 'AMERICAN CAP INC BUILDER F3 #: CFIHX',
    category: 'Large Cap - View',
    tier: 1,
    assetClass: 'Multiple',
    equitySector: 'Technology',
    asset: 'Value',
    selected: false,
  },
  {
    id: '5',
    name: 'AMERICAN CAP WRLD GRW & INC F3: FWGIX',
    category: 'Large Cap',
    tier: 1,
    assetClass: 'Multiple',
    equitySector: 'Financial',
    asset: 'Blend',
    selected: false,
  },
  {
    id: '6',
    name: 'AMERICAN CAPITAL WORLD BOND F3: WFBFX',
    category: 'Income',
    tier: 1,
    assetClass: 'Multiple',
    equitySector: 'Financial',
    asset: 'Taxable',
    selected: false,
  },
  {
    id: '7',
    name: 'AMERICAN EUPAC F3: FEUPX',
    category: 'Large Cap',
    tier: 1,
    assetClass: "Int'l Large Cap",
    equitySector: 'Financial',
    asset: 'Growth',
    selected: false,
  },
  {
    id: '8',
    name: 'AMERICAN FUNDAMENTAL INV F3: FUNFX',
    category: 'Large Cap',
    tier: 1,
    assetClass: 'Multiple',
    equitySector: 'Financial',
    asset: 'Blend',
    selected: false,
  },
  {
    id: '9',
    name: 'AMERICAN GLOBAL BALANCED F3 #: GFBLX',
    category: 'Large Cap - View',
    tier: 1,
    assetClass: 'Multiple',
    equitySector: 'Financial',
    asset: 'Blend',
    selected: false,
  },
];
